### ISSUE TITLE
Os pares de trade da classe Coin funcionam para a TAPI mas não para a API

### ISSUE THREAD

**Issue by esauvisky** [btrevizan/mb_api#1]
_Antes de mais nada obrigado pelo teu trabalho, me economizou muito tempo! :grin:_

O problema que encontrei é bem fácil de arrumar, mas como não tenho muita experiência com Python e menos ainda com OOB não vou fazer nenhum pull request do meu workaround porque é bem tosco, haha.

A API do MB pede uma chamada para:
`https://www.mercadobitcoin.net/api/<coin>/<method>/`
Exemplo:
`https://www.mercadobitcoin.net/api/BTC/ticker/`

Mas como a classe Coin do _labels.py_ tem os *pares* de trade embutidos, a API não funciona, pois ele tenta dar GET na API com o par e não só com a moeda. No caso, teu exemplo da API do README tenta fazer request da URL a seguir:
`https://www.mercadobitcoin.net/api//BRLBTC/ticker/`
Retornando um 404 e por sua vez quebrando o json.decode() posterior.

Se eu retirar o *BRL* da frente das moedas na classe Coin a API funciona, mas a TAPI para de funcionar. Na tua opinião, qual seria a solução mais robusta para esta situação?

**Comment by btrevizan** [comment]
Olá, @esauvisky 

Realmente, havia um erro nos labels. Já atualizei a versão do GitHub e o package no pypi. 
Agora há duas categorias de labels para moedas.

Coin.BTC, Coin.LTC, Coin.BCH para API;
Coin.BRLBTC, Coin.BRLLTC, Coin.BRLBCH para TAPI.

Ficou igual a nomenclatura em string e as pessoas podem perguntar "Por que não utilizar somente a string?". Com essas enumerações, é mais fácil manter um padrão. E como o MB ainda está crescendo e inserindo novas moedas (hopefully Bitcoin Gold entrará nessa), para atualizar a biblioteca, fica bem mais fácil.

Obrigado pelo contato. 
Se houver mais algum problema, por favor, entre em contato.
Faça um bom proveito com a API =D

Abraço!!!

**Comment by esauvisky** [comment]
Perfeita tua solução Bernardo, de classe! :grin:

Agora só me falta forkear este repositório e fazer uma biblioteca igualzinha para a API da FoxBit :stuck_out_tongue_closed_eyes:
